#!/bin/ksh
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2002-09, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Get environment variables: compiler options, directories names, ...
#-----------------------------------------------
#
. ../../../VARS
#
#-----------------------------------------------
# Nombre de niveaux désirés.
#-----------------------------------------------
#
#fic_niv="$dirloc/A_and_B/60_levels_ECMWF.lfa"
#fic_niv="$dirloc/A_and_B/31_levels_oper.lfa"
#fic_niv="$dirloc/A_and_B/41_levels_oper.lfa"
#fic_niv="$dirloc/A_and_B/31_levels_climat.lfa"
#fic_niv="$dirloc/A_and_B/266_levels.lfa"
fic_niv="$dirloc/A_and_B/91_levels_ECMWF.lfa"
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
#exe="non"
exe="oui"
if [ "$exe" = "oui" ] ; then
	rm -rf tmp Profiles ; mkdir tmp Profiles
fi
#
#-----------------------------------------------
# Compilation and execution on Linux.
#-----------------------------------------------
#  f90 +extend_source +cpp=yes -g $1 $LIBLFA
cl () {
  set -vx
  pgf90 -Mpreprocess -Mextend -r8 -i4 -Kieee -byteswapio info=inform $1 $LIBLFA
  shift
  args=$(echo "$@" | sed -e "s/^/'/" \
                 -e "s/  */' '/g" \
		  -e "s/\$/'/" )
  echo $args | a.out
}
#
#-----------------------------------------------
# Copy sources in the working directory.
#-----------------------------------------------
#
cp src/* tmp
cd tmp
#
#-----------------------------------------------
# Convert ASCII files into LFA files.
#-----------------------------------------------
#

if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Convert ASCII variable file into LFA file."
	echo " "
	cl ascii2lfa_var.F90 ../data_received_from_francoise/KIT_IDEAL/DATA/layer_idea_2days_advver_with_prescribed_rad.dat var.lfa
	lfaminm $dirloc/tmp/var.lfa
#exit
fi
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Convert ASCII Ts file into LFA file."
	echo " "
	cl ascii2lfa_Ts.F90 ../data_received_from_francoise/KIT_IDEAL/DATA/skin_t_idea_2days.dat $dirloc/tmp/Ts.lfa
	lfaminm $dirloc/tmp/Ts.lfa
fi
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Convert ASCII ps file into LFA file."
	echo " "
	cl ascii2lfa_ps.F90 ../data_received_from_francoise/KIT_IDEAL/DATA/surface_idea_2days.dat \
		 $dirloc/tmp/ps.lfa
	lfaminm $dirloc/tmp/ps.lfa
fi
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Convert ASCII flux file into LFA file."
	echo " "
	cl ascii2lfa_flux.F90 ../data_received_from_francoise/new_flux_ideal.dat \
		 $dirloc/tmp/flux.lfa
	lfaminm $dirloc/tmp/flux.lfa
fi
#
#-----------------------------------------------
# Fusion de tous les fichiers LFA.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Merge variables, Ts, ps and flux into a single LFA file."
	echo " "
	lfareu $dirloc/tmp/var.lfa $dirloc/tmp/Ts.lfa pivot
	lfareu pivot $dirloc/tmp/ps.lfa pivot2
	lfareu pivot2 $dirloc/tmp/flux.lfa var.lfa
	lfaminm $dirloc/tmp/var.lfa
fi
#
#-----------------------------------------------
# Interpolation verticale.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Vertical interpolation of variables to a prescribed vertical grid."
	echo " "
	cl interpol_vert.F90 $fic_niv \
		$dirloc/tmp/var.lfa \
		$dirloc/tmp/var_int_vert.lfa
	lfaminm $dirloc/tmp/var_int_vert.lfa
fi
#
#-----------------------------------------------
# Interpolation temporelle.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Temporal interpolation of variables to a prescribed temporal grid."
	echo " "
	cl interpol_horiz.F90 $dirloc/tmp/var_int_vert.lfa \
		$dirloc/tmp/var_int_vert_horiz.lfa
	lfaminm $dirloc/tmp/var_int_vert_horiz.lfa
fi
#
#-----------------------------------------------
# Combinaison variables et flux.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Combine fluxes and variables in a single file."
	echo " "
	lfareu $dirloc/tmp/var_int_vert_horiz.lfa \
		$dirloc/tmp/Ts.lfa \
		pivot
	lfareu pivot \
		$dirloc/tmp/flux.lfa \
		$dirloc/tmp/var_flux.lfa
	lfaminm $dirloc/tmp/var_flux.lfa
fi
#
#-----------------------------------------------
# Création du LFA final, prêt pour le M1D.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Create final LFA file, ready for use in the SCM:"
	echo "	- required units (SI)"
	echo "	- required article names "
	echo "	- one file at each sampling time"
	echo " "
	cl rename_articles.F90 $dirloc/tmp/var_flux.lfa \
		$dirloc/Profiles
	lfaminm $dirloc/Profiles/Profile.000.00.lfa
fi
#########
exe=non
#########
#
#-----------------------------------------------
# Dans ce LFA final, on remplace les profils de T et qv par ceux prévus par le CRM MESO-NH.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Replace T and qv field by those predicted by the CRM MESO-NH:"
	echo " "
	cd $dirloc/Profiles
	for f in Profile*.lfa
	do
		if [ "$f" != "Profile.000.00.lfa" ] ; then
			#
			#-----------------------------------------------
			# Le profil de T et qv initial est laissé tel quel (observé),
			# tandis que les profils suivants sont forcés 
			# à ceux prévus par le CRM MESO-NH.
			#-----------------------------------------------
			#
			base=`basename $f`
			lfareu $f ../../data_crm_predictions/$base toto
			mv toto $f
		fi
	done
fi
#
#-----------------------------------------------
# Dans ce LFA final, on ajoute les bilans de qv, pour diagnostic.
#-----------------------------------------------
#
if [ "$exe" = "oui" ] ; then
	echo " "
	echo "-------------------------------------------------------------------"
	echo " "
	echo "Add qv budgets, as coming out from the CRM."
	echo " "
	cd $dirloc/Profiles
	for f in Profile*.lfa
	do
		if [ "$f" != "Profile.000.00.lfa" ] ; then
			#
			#-----------------------------------------------
			# Le profil de T et qv initial est laissé tel quel (observé),
			# tandis que dans les profils suivants on ajoute
			# les termes du bilan de qv CRM.
			#-----------------------------------------------
			#
			base=`basename $f`
			fadd="../../data_crm_predictions/qv_budget/$base"
			if test -s $fadd
			then
				lfareu $f $fadd toto
				mv toto $f
			fi
		fi
		#
		#-----------------------------------------------
		# On efface les fichiers produits, pour les échéances >= 24h.
		#-----------------------------------------------
		#
		zheure=`expr $f | cut -c9-14`
		iheure=`cals -fi4 "$zheure int"`
		if [ $iheure -ge 24 ] ; then
			echo "$f removed."
			rm $f
		fi
	done
fi
#
#-----------------------------------------------
# Epilogue.
#-----------------------------------------------
#
cd $dirloc
ls -lrt
