#!/usr/bin/env python3
# -*- coding:UTF-8 -*-
# Copyright (c) Météo France (2014-)
# This software is governed by the CeCILL-C license under French law.
# http://www.cecill.info

#saveall = True
saveall = False

#var2save = ['pfull','zfull','theta','qv','cl']

var2save = ['pfull','zfull','theta','ta','qv','ua','va','wap','ql','qi','qr','qsn','cl','clt','prw','pr','hfls','hfss','ts','hur','Q1','Q2','qlc','qic','qrc','qsnc','tke','wa_up','mf_up','alpha_up','ustar','z0','dTv_up','ta_up','qv_up','ent_up','det_up','b_up','ent_up_org','ent_up_turb','det_up_org','det_up_turb','lwp','tnta_turb','tnta_conv','tnta_micro','tnqv_turb','tnqv_micro','tnqv_conv','dw_buoy','dw_fric','dw_Kd','dw_entr','dw_transp','Q11','Q11min','Q11max','sigs','PQCS0_ACTURB','PNEBS0_ACTURB','PQLI0_ACTURB','ZLMECTF_ACTURB','ZECTF_ACTURB','qsurf','ZAUTOL_ACPLUIZ','ZAUTOI_ACPLUIZ','PFCSQL_ACPLUIZ','PFCSQN_ACPLUIZ','PFPFPL_ACPLUIZ','PFPFPN_ACPLUIZ','TNQV_AUTOL_ACPLUIZ','TNQV_AUTON_ACPLUIZ','TNQV_CORL_ACPLUIZ','TNQV_CORN_ACPLUIZ','PFCSQL_ACPLUIZ_IN','PFCSQN_ACPLUIZ_IN','ZFLUXCOR_ACPLUIZ','ZDT_ACPLUIZ','PQCS_ACPLUIZ','ZDQL_ACPLUIZ','ZDQI_ACPLUIZ','ZLMECTF_ACTURB','ZECTF_ACTURB','AIPCMT','KNND','KNLAB','PALF','ZS15','ZS16','IKUO5','IKUO6','INIVBAC','ZCAPE','IBAC','ZS15V0','ZTAU','KNLAB_ACMTUD','KNLABV0_ACMTUD','KNLABV1_ACMTUD','KNND_ACMTUD','KNNDV0_ACMTUD','KNNDV1_ACMTUD']

fluxes = ['PDIFTQ','PDIFCQ',
          'PFRMQ',
          'PFCCQL','PFCCQN','PFCSQL','PFCSQN',
          'PFCQNG',
          'PFECL','PFECN','PFESL','PFESN',
          'PFCHQ',
          'PDIFTQL','PDIFCQL',
          'PFCQLNG',
          'PFACL','PFASL',
          'PSEDIQL',
          'PDIFTQI','PDIFCQI',
          'PFCQING',
          'PFACN','PFASN',
          'PSEDIQI',
          'ZFPL','PFCQRNG',
          'ZFPN','PFCQSNG',
          'PFTKE']
var2save += [s+'_CPTEND_NEW' for s in fluxes]

variables = ['ZQLCORP','ZQICORP','ZFCQNG','ZQCORP','PFCQNG_IN','PFCQNG_OUT']
var2save += [s+'_QNGCOR' for s in variables]
variables = ['PFCQVNG_IN','PFCQVNG_01','PFCQVNG_OUT','PQ_IN','PQ_OUT','PDIFTQ_IN','PDIFTQ_01','PDIFTQ_OUT']
var2save += [s+'_APLPAR' for s in variables]
variables = ['PDIFTQ_IN','PDIFTQ_01','PDIFTQ_02','PDIFTQ_03','PDIFTQ_OUT']
var2save += [s+'_MF_PHYS' for s in variables]
variables = ['PFEV_IN','PXHROV_IN','POID_IN','PCFAQ_IN','PCFBQ_IN','PKTROV_IN','PKQROV_IN','PDIFTQ_OUT','PQT_IN']
var2save += [s+'_ACDIFV2' for s in variables]
variables = ['PDIFCQ','PDIFCQL','PDIFCQI','PDIFCQLC','PDIFCQIC','PDIFCS','PDIFTH','PFCCQL','PFCCQN','PSTRCU','PSTRCV','PFIMCC','PFPEVPCL','PFPEVPCN','PFPLCL','PFPLCN','PFPFPCL','PFPFPCN','PFEDQLC','PFEDQIC','PFEDQRC','PFEDQSC','PFCNEGQLC','PFCNEGQIC','PFCNEGQRC','PFCNEGQSC']
var2save += [s+'_ACPCMT' for s in variables]
var2save += ['PALPH_IN_ACMTUD','PAPHI_IN_ACMTUD','PAPHIF_IN_ACMTUD','PAPRS_IN_ACMTUD','PAPRSF_IN_ACMTUD','PCP_IN_ACMTUD','PLH_IN_ACMTUD','PR_IN_ACMTUD','PDELP_IN_ACMTUD','PLNPR_IN_ACMTUD','PQ_IN_ACMTUD','PQLIS_IN_ACMTUD','PQSAT_IN_ACMTUD','PQW_IN_ACMTUD','PRDELP_IN_ACMTUD','PCVGQ_IN_ACMTUD','PT_IN_ACMTUD','PTW_IN_ACMTUD','PU_IN_ACMTUD','PV_IN_ACMTUD','PSMOOTRA_IN_ACMTUD','PTKE_IN_ACMTUD','PEVAPO_IN_ACMTUD','PGM_IN_ACMTUD','PTS_IN_ACMTUD','PDIFCQ_IN_ACMTUD','PDIFCQL_IN_ACMTUD','PDIFCQI_IN_ACMTUD','PDIFCS_IN_ACMTUD','PDIFCTH_IN_ACMTUD','PPRODTH_IN_ACMTUD','PFCCQL_IN_ACMTUD','PFCCQI_IN_ACMTUD','PSTRCU_IN_ACMTUD','PSTRCV_IN_ACMTUD','PMF_UP_IN_ACMTUD','PTU_IN_ACMTUD','PQU_IN_ACMTUD','PFHMLTS_IN_ACMTUD','PFPLCL_IN_ACMTUD','PFPLCN_IN_ACMTUD','PFPEVPCL_IN_ACMTUD','PFPEVPCN_IN_ACMTUD','PFHEVPP_IN_ACMTUD','PUDAL_IN_ACMTUD','PUDOM_IN_ACMTUD','PDDAL_IN_ACMTUD','PDDOM_IN_ACMTUD','PDIFCQ_OUT_ACMTUD','PDIFCQL_OUT_ACMTUD','PDIFCQI_OUT_ACMTUD','PDIFCS_OUT_ACMTUD','PDIFCTH_OUT_ACMTUD','PPRODTH_OUT_ACMTUD','PFCCQL_OUT_ACMTUD','PFCCQI_OUT_ACMTUD','PSTRCU_OUT_ACMTUD','PSTRCV_OUT_ACMTUD','PMF_UP_OUT_ACMTUD','PTU_OUT_ACMTUD','PQU_OUT_ACMTUD','PFHMLTS_OUT_ACMTUD','PFPLCL_OUT_ACMTUD','PFPLCN_OUT_ACMTUD','PFPEVPCL_OUT_ACMTUD','PFPEVPCN_OUT_ACMTUD','PFHEVPP_OUT_ACMTUD','PUDAL_OUT_ACMTUD','PUDOM_OUT_ACMTUD','PDDAL_OUT_ACMTUD','PDDOM_OUT_ACMTUD','KNLAB_OUT_ACMTUD','KNND_OUT_ACMTUD','PALF_OUT_ACMTUD','PCAPE_OUT_ACMTUD','PMU_OUT_ACMTUD','PMD_OUT_ACMTUD','PNEBC_OUT_ACMTUD','PQLIC_OUT_ACMTUD','PENTR_U_OUT_ACMTUD','PDETR_U_OUT_ACMTUD','PENTR_D_OUT_ACMTUD','PDETR_D_OUT_ACMTUD','PENTR_U_TOT_OUT_ACMTUD']
var2save += ['PALPH_IN_ACMTUD','PAPHI_IN_ACMTUD','PAPHIF_IN_ACMTUD','PAPRS_IN_ACMTUD','PAPRSF_IN_ACMTUD','PVERVEL_IN_ACMTUD','PCP_IN_ACMTUD','PLH_IN_ACMTUD','PR_IN_ACMTUD','PDELP_IN_ACMTUD','PLNPR_IN_ACMTUD','PQ_IN_ACMTUD','PQLIS_IN_ACMTUD','PQSAT_IN_ACMTUD','PQW_IN_ACMTUD','PRDELP_IN_ACMTUD','PCVGQ_IN_ACMTUD','PT_IN_ACMTUD','PTW_IN_ACMTUD','PU_IN_ACMTUD','PV_IN_ACMTUD','PSMOOTRA_IN_ACMTUD','PTKE_IN_ACMTUD','PGM_IN_ACMTUD','PTS_IN_ACMTUD','KNLAB_IN_ACMTUD','KNND_IN_ACMTUD','PALF_IN_ACMTUD','PDIFCQ_IN_ACMTUD','PDIFCQL_IN_ACMTUD','PDIFCQI_IN_ACMTUD','PDIFCS_IN_ACMTUD','PDIFCTH_IN_ACMTUD','PPRODTH_IN_ACMTUD','PFCCQL_IN_ACMTUD','PFCCQI_IN_ACMTUD','PSTRCU_IN_ACMTUD','PSTRCV_IN_ACMTUD','PTU_IN_ACMTUD','PQU_IN_ACMTUD','PFHMLTS_IN_ACMTUD','PFPLCL_IN_ACMTUD','PFPLCN_IN_ACMTUD','PFPEVPCL_IN_ACMTUD','PFPEVPCN_IN_ACMTUD','PFHEVPP_IN_ACMTUD','PUDAL_IN_ACMTUD','PUDOM_IN_ACMTUD','PDDAL_IN_ACMTUD','PDDOM_IN_ACMTUD','KNLAB_OUT_ACMTUD','KNND_OUT_ACMTUD','PALF_OUT_ACMTUD','PDIFCQ_OUT_ACMTUD','PDIFCQL_OUT_ACMTUD','PDIFCQI_OUT_ACMTUD','PDIFCS_OUT_ACMTUD','PDIFCTH_OUT_ACMTUD','PPRODTH_OUT_ACMTUD','PFCCQL_OUT_ACMTUD','PFCCQI_OUT_ACMTUD','PSTRCU_OUT_ACMTUD','PSTRCV_OUT_ACMTUD','PTU_OUT_ACMTUD','PQU_OUT_ACMTUD','PFHMLTS_OUT_ACMTUD','PFPLCL_OUT_ACMTUD','PFPLCN_OUT_ACMTUD','PFPEVPCL_OUT_ACMTUD','PFPEVPCN_OUT_ACMTUD','PFHEVPP_OUT_ACMTUD','PUDAL_OUT_ACMTUD','PUDOM_OUT_ACMTUD','PDDAL_OUT_ACMTUD','PDDOM_OUT_ACMTUD','PCAPE_OUT_ACMTUD','PMF_UP_OUT_ACMTUD','PMU_OUT_ACMTUD','PMD_OUT_ACMTUD','PNEBC_OUT_ACMTUD','PQLIC_OUT_ACMTUD','PENTR_U_OUT_ACMTUD','PDETR_U_OUT_ACMTUD','PENTR_D_OUT_ACMTUD','PDETR_D_OUT_ACMTUD','PENTR_U_TOT_OUT_ACMTUD','PALF_CAPE_OUT_ACMTUD','PALF_CVGQ_OUT_ACMTUD']
var2save += ['ZPUOM_IN_MF_PHYS','ZPUOM1_IN_MF_PHYS','ZPUOM_OUT_MF_PHYS','ZPUOM1_OUT_MF_PHYS']
#var2save = ['pf','zf','theta','temp','qv','u','v','wap','ql','qr','rneb','cc','prw','rain','lhf','shf','tsurf',]
#var2save = ['pf','zf','theta','temp','qv','rneb']
var2save += ['PNEBS_ACTURB', 'PQCS_ACTURB','PQLI_ACTURB']

convert2p = False
#convert2z = True
convert2z = False

convertkday = False
convertpday = False
convertzday = False

convertk1h = False
convertp1h = False
convertz1h = False

convertk3h = False # not coded for True
convertp3h = False
convertz3h = False # not coded for True

# Pour convert2p, niveau en hPa
levout = []
for i in range(1,41):
  levout.append(i*25.)
levout.reverse()

# Pour convert2z, niveau en m
levoutz = []
for i in range(0,401):
  levoutz.append(i*50.)
levoutz.reverse()

# Niveau de print (0, 1 ou 2)
verbose = 2
