# acadfa makefile

FC	=	g95
FFLAGS	 = -r8 -i4  -DLX86P  -fendian=big -fno-second-underscore  -g -O0
F90FLAGS	 = -r8 -i4  -DLX86P  -fendian=big -fno-second-underscore -g -O0
EXEC	=	acadfa_exe

OBJS	=	acadfa1D_main.o \
		acadfa_sueframe.o \
		real2spec.o \
		empty.o 

XRD	=	libxrd.a libgribex.a libmpidummy.a
LIBS	=	$(XRD) 

%.o:%.F90
	$(FC) $(F90FLAGS) -c $<

all:	$(OBJS)
	$(FC) $(F90FLAGS) -o $(EXEC) $(OBJS) $(LIBS)

clean:
	/bin/rm -f $(EXEC) $(OBJS)

