#!/usr/bin/env python3
# -*- coding:UTF-8 -*-
# Copyright (c) Météo France (2014-)
# This software is governed by the CeCILL-C license under French law.
# http://www.cecill.info

# 1. Dynamical and thermodynamical variables
# 2. Cloud variables
# 3. Precipitation variables
# 4. Radiation variables
# 5. Surface turbulent fluxes
# 6. Vertically-integrated variables
# 7. Near-surface variables
# 8. Physical tendencies
# 9. Physics fluxes
# 10. Forcing tendencies
# 11. Water and energy budget
# 12. Gaseous variables
# 13. Convective variables
# 14. Wake variables
# 15. Turbulence variables
# 16. COSP variables
# 16.1 COSP input variables
# 17. Miscellanenous

variables = {
# 1. Dynamical and thermodynamical variables
    'hur'               : {'varname':               'PRH', 'units':                 '-', 'coef':         1, 'name':'Relative Humidity'}, 
    'pf'                : {'varname':            'PAPRSF', 'units':                'Pa', 'coef':         1, 'name':'Pressure on Full Levels'}, 
    'ph'                : {'varname':             'PAPRS', 'units':                'Pa', 'coef':         1, 'name':'Pressure on Half Levels'}, 
    'qi'                : {'varname':             'PQICE', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Cloud Ice Water'}, 
    'qic'               : {'varname':           'PQICONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Convective Ice Water'}, 
    'qishc'             : {'varname':         'PQISHCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Shallow Convection Ice Water'}, 
    'ql'                : {'varname':              'PQLI', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Cloud Liquid Water'}, 
    'qlc'               : {'varname':           'PQLCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Convective Liquid Water'}, 
    'qlshc'             : {'varname':         'PQLSHCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Shallow Convection Liquid Water'}, 
    'qr'                : {'varname':               'PQR', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Rain'}, 
    'qrc'               : {'varname':           'PQRCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Convective Rain'}, 
    'qrshc'             : {'varname':         'PQRSHCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Shallow Convection Rain'}, 
    'qsat'              : {'varname':             'PQSAT', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Humidity at Saturation'}, 
    'qsn'               : {'varname':              'PQSN', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Snow'}, 
    'qsnc'              : {'varname':           'PQSCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Convective Snow'}, 
    'qsnshc'            : {'varname':         'PQSSHCONV', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Mass of Shallow Convection Snow'}, 
    'qv'                : {'varname':                'PQ', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Humidity'}, 
    'rho'               : {'varname':               'RHO', 'units':             'kg/m3', 'coef':         1, 'name':'Air Volumic Mass'}, 
    'temp'              : {'varname':                'PT', 'units':                 'K', 'coef':         1, 'name':'Air Temperature'}, 
    'theta'             : {'varname':             'THETA', 'units':                 'K', 'coef':         1, 'name':'Potential Temperature'}, 
    'thl'               : {'varname':            'THETAL', 'units':                 'K', 'coef':         1, 'name':'Liquid Potential Temperature'}, 
    'thlv'              : {'varname':           'THETAVL', 'units':                 'K', 'coef':         1, 'name':'Virtual Potential Temperature'}, 
    'thv'               : {'varname':            'THETAV', 'units':                 'K', 'coef':         1, 'name':'Virtual Potential Temperature'}, 
    'tke'               : {'varname':              'PECT', 'units':             'm2/s2', 'coef':         1, 'name':'Turbulent Kinetic Energy'}, 
    'u'                 : {'varname':                'PU', 'units':               'm/s', 'coef':         1, 'name':'Zonal Wind'}, 
    'v'                 : {'varname':                'PV', 'units':               'm/s', 'coef':         1, 'name':'Meridional Wind'}, 
    'wa'                : {'varname':                'ZW', 'units':               'm/s', 'coef':         1, 'name':'Vertical Velocity'}, 
    'wap'               : {'varname':            'ZOMEGA', 'units':              'Pa/s', 'coef':         1, 'name':'Vertical Pressure Velocity'}, 
    'zf'                : {'varname':            'PAPHIF', 'units':                 'm', 'coef':0.10197162129779283, 'name':'Geopotential on Full Levels'}, 
    'zh'                : {'varname':             'PAPHI', 'units':                 'm', 'coef':0.10197162129779283, 'name':'Geopotential on Half Levels'}, 
# 2. Cloud variables
    'cc'                : {'varname':             'PCLCT', 'units':                 '-', 'coef':         1, 'name':'Total Cloud Fraction'}, 
    'cls'               : {'varname':             'ZNEBS', 'units':                 '-', 'coef':         1, 'name':'Stratiform Cloud Fraction'}, 
    'cltc'              : {'varname':             'PCLCC', 'units':                 '-', 'coef':         1, 'name':'Total Convective Cloud Fraction'}, 
    'clth'              : {'varname':             'PCLCH', 'units':                 '-', 'coef':         1, 'name':'Total High Cloud Fraction'}, 
    'cltl'              : {'varname':             'PCLCL', 'units':                 '-', 'coef':         1, 'name':'Total Low Cloud Fraction'}, 
    'cltm'              : {'varname':             'PCLCM', 'units':                 '-', 'coef':         1, 'name':'Total Mid Cloud Fraction'}, 
    'rneb'              : {'varname':              'PNEB', 'units':                 '-', 'coef':         1, 'name':'Cloud Fraction'}, 
# 3. Precipitation variables
    'ppr'               : {'varname':          'PREC_TOT', 'units':           'kg/m2/s', 'coef':         1, 'name':'Total Precipitation Profile'}, 
    'pprc'              : {'varname':            'PREC_C', 'units':           'kg/m2/s', 'coef':         1, 'name':'Convective Precipitation Profile'}, 
    'pprls'             : {'varname':           'PREC_LS', 'units':           'kg/m2/s', 'coef':         1, 'name':'Large-Scale Precipitation Profile'}, 
    'prc'               : {'varname':        'PRECS_CONV', 'units':           'kg/m2/s', 'coef':         1, 'name':'Surface Convective Precipitation'}, 
    'precc'             : {'varname':            'PFPLCL', 'units':           'kg/m2/s', 'coef':         1, 'name':'Convective Precipitation Flux'}, 
    'precls'            : {'varname':            'PFPLSL', 'units':           'kg/m2/s', 'coef':         1, 'name':'Large-Scale Precipitation Flux'}, 
    'prls'              : {'varname':          'PRECS_LS', 'units':           'kg/m2/s', 'coef':         1, 'name':'Surface Large-Scale Precipitation'}, 
    'rain'              : {'varname':         'PRECS_TOT', 'units':           'kg/m2/s', 'coef':         1, 'name':'Surface Precipitation'}, 
    'snowc'             : {'varname':            'PFPLCN', 'units':           'kg/m2/s', 'coef':         1, 'name':'Convective Snow Flux'}, 
    'snowls'            : {'varname':            'PFPLSN', 'units':           'kg/m2/s', 'coef':         1, 'name':'Large-Scale Snow Flux'}, 
# 4. Radiation variables
    'I0'                : {'varname':               'ZI0', 'units':              'W/m2', 'coef':         1, 'name':'Solar irradiance'}, 
    'LWd'               : {'varname':               'LWd', 'units':              'W/m2', 'coef':         1, 'name':'Downward LW Flux'}, 
    'LWdcs'             : {'varname':             'LWdcs', 'units':              'W/m2', 'coef':         1, 'name':'CS Downward LW Flux'}, 
    'LWnet'             : {'varname':             'PFRTH', 'units':              'W/m2', 'coef':         1, 'name':'Net LW Flux'}, 
    'LWu'               : {'varname':               'LWu', 'units':              'W/m2', 'coef':         1, 'name':'Upward LW Flux'}, 
    'LWucs'             : {'varname':             'LWucs', 'units':              'W/m2', 'coef':         1, 'name':'CS Upward LW Flux'}, 
    'SWd'               : {'varname':               'SWd', 'units':              'W/m2', 'coef':         1, 'name':'Downward SW Flux'}, 
    'SWdcs'             : {'varname':             'SWdcs', 'units':              'W/m2', 'coef':         1, 'name':'CS Downward SW Flux'}, 
    'SWnet'             : {'varname':             'PFRSO', 'units':              'W/m2', 'coef':         1, 'name':'Net SW Flux'}, 
    'SWu'               : {'varname':               'SWu', 'units':              'W/m2', 'coef':         1, 'name':'Upward SW Flux'}, 
    'SWucs'             : {'varname':             'SWucs', 'units':              'W/m2', 'coef':         1, 'name':'CS Upward SW Flux'}, 
    'alb_ss'            : {'varname':            'SW_ALB', 'units':                 '-', 'coef':         1, 'name':'SW Surface Albedo'}, 
    'mu1'               : {'varname':              'ZMU0', 'units':                 '-', 'coef':         1, 'name':'Sinus of zenith angle'}, 
    'mueff'             : {'varname':           'ZMU0EFF', 'units':                 '-', 'coef':         1, 'name':'Sinus of effective zenith angle'}, 
    'rlds'              : {'varname':        'LW_Surf_dn', 'units':              'W/m2', 'coef':         1, 'name':'Downward LW Radiation at Surface'}, 
    'rldscs'            : {'varname':     'LW_Surf_cs_dn', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Downward LW Radiation at Surface'}, 
    'rldt'              : {'varname':         'LW_TOA_dn', 'units':              'W/m2', 'coef':         1, 'name':'Downward LW Radiation at TOA'}, 
    'rldtcs'            : {'varname':      'LW_TOA_cs_dn', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Downward LW Radiation at TOA'}, 
    'rls'               : {'varname':           'LW_Surf', 'units':              'W/m2', 'coef':         1, 'name':'LW Radiation at Surface'}, 
    'rlscs'             : {'varname':        'LW_Surf_cs', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky LW Radiation at Surface'}, 
    'rlt'               : {'varname':            'LW_TOA', 'units':              'W/m2', 'coef':         1, 'name':'LW Radiation at TOA'}, 
    'rltcs'             : {'varname':         'LW_TOA_cs', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky LW Radiation at TOA'}, 
    'rlus'              : {'varname':        'LW_Surf_up', 'units':              'W/m2', 'coef':         1, 'name':'Upward LW Radiation at Surface'}, 
    'rluscs'            : {'varname':     'LW_Surf_cs_up', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Upward LW Radiation at Surface'}, 
    'rlut'              : {'varname':         'LW_TOA_up', 'units':              'W/m2', 'coef':         1, 'name':'Upward LW Radiation at TOA'}, 
    'rlutcs'            : {'varname':      'LW_TOA_cs_up', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Upward LW Radiation at TOA'}, 
    'rsds'              : {'varname':        'SW_Surf_dn', 'units':              'W/m2', 'coef':         1, 'name':'Downward SW Radiation at Surface'}, 
    'rsdscs'            : {'varname':     'SW_Surf_cs_dn', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Downward SW Radiation at Surface'}, 
    'rsdt'              : {'varname':         'SW_TOA_dn', 'units':              'W/m2', 'coef':         1, 'name':'Downward SW Radiation at TOA'}, 
    'rsdtcs'            : {'varname':      'SW_TOA_cs_dn', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Downward SW Radiation at TOA'}, 
    'rss'               : {'varname':           'SW_Surf', 'units':              'W/m2', 'coef':         1, 'name':'SW Radiation at Surface'}, 
    'rsscs'             : {'varname':        'SW_Surf_cs', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky SW Radiation at Surface'}, 
    'rst'               : {'varname':            'SW_TOA', 'units':              'W/m2', 'coef':         1, 'name':'SW Radiation at TOA'}, 
    'rstcs'             : {'varname':         'SW_TOA_cs', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky SW Radiation at TOA'}, 
    'rsus'              : {'varname':        'SW_Surf_up', 'units':              'W/m2', 'coef':         1, 'name':'Upward SW Radiation at Surface'}, 
    'rsuscs'            : {'varname':     'SW_Surf_cs_up', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Upward SW Radiation at Surface'}, 
    'rsut'              : {'varname':         'SW_TOA_up', 'units':              'W/m2', 'coef':         1, 'name':'Upward SW Radiation at TOA'}, 
    'rsutcs'            : {'varname':      'SW_TOA_cs_up', 'units':              'W/m2', 'coef':         1, 'name':'Clear-sky Upward SW Radiation at TOA'}, 
# 5. Surface turbulent fluxes
    'Cd'                : {'varname':               'ZCD', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Coefficient for Wind'}, 
    'Cdn'               : {'varname':              'ZCDN', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Neutral Coefficient for Wind'}, 
    'Ce'                : {'varname':               'ZCE', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Coefficient for Water Vapor'}, 
    'Cen'               : {'varname':              'ZCEN', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Neutral Coefficient for Water Vapor'}, 
    'Ch'                : {'varname':               'ZCH', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Coefficient for Heat'}, 
    'Chn'               : {'varname':              'ZCHN', 'units':                 '-', 'coef':         1, 'name':'Surface Exchange Neutral Coefficient for Heat'}, 
    'Ugr'               : {'varname':               'UGR', 'units':               'm/s', 'coef':         1, 'name':'Wind gustiness due to precipitation'}, 
    'evap'              : {'varname':             'PFEVL', 'units':           'kg/m2/s', 'coef':         1, 'name':'Evaporation over liquid water (or wet soil)'}, 
    'evapi'             : {'varname':             'PFEVI', 'units':           'kg/m2/s', 'coef':         1, 'name':'Evaporation over frozen soil'}, 
    'evapn'             : {'varname':             'PFEVN', 'units':           'kg/m2/s', 'coef':         1, 'name':'Evaporation over snow (or ice) and frozen soil'}, 
    'lhf'               : {'varname':             'PFCLL', 'units':              'W/m2', 'coef':         1, 'name':'Surface Latent Heat Flux'}, 
    'lhfn'              : {'varname':             'PFCLN', 'units':              'W/m2', 'coef':         1, 'name':'Surface Latent Heat Flux over Snow or Ice'}, 
    'qsurf'             : {'varname':               'PQS', 'units':             'kg/kg', 'coef':         1, 'name':'Surface saturated specific humidity (qsat(SST))'}, 
    'shf'               : {'varname':              'PFCS', 'units':              'W/m2', 'coef':         1, 'name':'Surface Sensible Heat Flux'}, 
    'tauu'              : {'varname':              'PSFU', 'units':        'kg m-1 s-2', 'coef':         1, 'name':'Surface zonal stress'}, 
    'tauv'              : {'varname':              'PSFV', 'units':        'kg m-1 s-2', 'coef':         1, 'name':'Surface meridional stress'}, 
    'tsurf'             : {'varname':               'PTS', 'units':                 'K', 'coef':         1, 'name':'Surface temperature (SST)'}, 
    'ustar'             : {'varname':            'ZUSTAR', 'units':               'm/s', 'coef':         1, 'name':'ustar'}, 
    'z0'                : {'varname':               'PZ0', 'units':                 'm', 'coef':         1, 'name':'z0'}, 
    'z0h'               : {'varname':              'PZ0H', 'units':                 'm', 'coef':         1, 'name':'z0h'}, 
    'zref'              : {'varname':             'PZREF', 'units':                 'm', 'coef':         1, 'name':'Altitude of the first atmospheric level'}, 
# 6. Vertically-integrated variables
    'cwp'               : {'varname':               'CWP', 'units':             'kg/m2', 'coef':         1, 'name':'Cloud Water Path'}, 
    'iwp'               : {'varname':               'IWP', 'units':             'kg/m2', 'coef':         1, 'name':'Ice Water Path'}, 
    'lwp'               : {'varname':               'LWP', 'units':             'kg/m2', 'coef':         1, 'name':'Liquid Water Path'}, 
    'prw'               : {'varname':               'WVP', 'units':             'kg/m2', 'coef':         1, 'name':'Precipitable Water'}, 
# 7. Near-surface variables
    'hurs'              : {'varname':            'PRHCLS', 'units':                 '-', 'coef':         1, 'name':'2-meter Relative Humidity'}, 
    'huss'              : {'varname':             'PQCLS', 'units':             'kg/kg', 'coef':         1, 'name':'2-meter Specific Humidity'}, 
    'pblh'              : {'varname':              'HCLA', 'units':                 'm', 'coef':         1, 'name':'Planetary Boundary Layer Height'}, 
    't2m'               : {'varname':             'PTCLS', 'units':                 'K', 'coef':         1, 'name':'2-meter Air Temperature'}, 
    'uas'               : {'varname':             'PUCLS', 'units':               'm/s', 'coef':         1, 'name':'10-meter Zonal Wind'}, 
    'vas'               : {'varname':             'PVCLS', 'units':               'm/s', 'coef':         1, 'name':'10-meter Meridional Wind'}, 
# 8. Physical tendencies
    'Q1'                : {'varname':                'Q1', 'units':               'K/s', 'coef':         1, 'name':'Apparent Heat Source'}, 
    'Q2'                : {'varname':                'Q2', 'units':               'K/s', 'coef':         1, 'name':'Apparent Moisture Sink'}, 
    'QRad'              : {'varname':              'QRad', 'units':               'K/s', 'coef':         1, 'name':'Radiative Heating Rate'}, 
    'tendh'             : {'varname':             'TENDH', 'units':                 '-', 'coef':         1, 'name':'TENDH'}, 
    'tendq'             : {'varname':             'TENDQ', 'units':                 '-', 'coef':         1, 'name':'TENDQ'}, 
    'tendu'             : {'varname':             'TENDU', 'units':                 '-', 'coef':         1, 'name':'TENDU'}, 
    'tendv'             : {'varname':             'TENDV', 'units':                 '-', 'coef':         1, 'name':'TENDV'}, 
    'tnqi'              : {'varname':            'TENDQI', 'units':           'kg/kg/s', 'coef':         1, 'name':'Ice Water Tendency due to Physics'}, 
    'tnqic'             : {'varname':        'TENDQICONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Convective Ice Water Tendency due to Physics'}, 
    'tnqishc'           : {'varname':      'TENDQISHCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Shallow Convection Ice Water Tendency due to Physics'}, 
    'tnql'              : {'varname':            'TENDQL', 'units':           'kg/kg/s', 'coef':         1, 'name':'Liquid Water Tendency due to Physics'}, 
    'tnqlc'             : {'varname':        'TENDQLCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Convective Liquid Water Tendency due to Physics'}, 
    'tnqlshc'           : {'varname':      'TENDQLSHCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Shallow Convection Liquid Water Tendency due to Physics'}, 
    'tnqr'              : {'varname':            'TENDQR', 'units':           'kg/kg/s', 'coef':         1, 'name':'Rain Tendency due to Physics'}, 
    'tnqrc'             : {'varname':        'TENDQRCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Convective Rain Tendency due to Physics'}, 
    'tnqrshc'           : {'varname':      'TENDQRSHCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Shallow Convection Rain Tendency due to Physics'}, 
    'tnqsn'             : {'varname':            'TENDQS', 'units':           'kg/kg/s', 'coef':         1, 'name':'Snow Tendency due to Physics'}, 
    'tnqsnc'            : {'varname':        'TENDQSCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Convective Snow Tendency due to Physics'}, 
    'tnqsnc'            : {'varname':        'TENDQSCONV', 'units':           'kg/kg/s', 'coef':         1, 'name':'Convective Snow Tendency due to Physics'}, 
    'tnqt'              : {'varname':            'TENDQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Physics'}, 
    'tnqtc'             : {'varname':           'TENDCQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Convection'}, 
    'tnqtd'             : {'varname':           'TENDMQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Other Processes'}, 
    'tnqtlscp'          : {'varname':           'TENDSQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Large-scale Condensation and Precipitation'}, 
    'tnqtpbl'           : {'varname':           'TENDTQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Turbulence'}, 
    'tnqtshc'           : {'varname':         'TENDSHCQT', 'units':           'kg/kg/s', 'coef':         1, 'name':'Total Water Tendency due to Shallow Convection'}, 
    'tnqvc'             : {'varname':            'TENDCQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Convection'}, 
    'tnqvd'             : {'varname':            'TENDMQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Other Processes'}, 
    'tnqvlscp'          : {'varname':            'TENDSQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Large-scale Condensation and Precipitation'}, 
    'tnqvpbl'           : {'varname':            'TENDTQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Turbulence'}, 
    'tnqvshc'           : {'varname':          'TENDSHCQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Shallow Convection'}, 
    'tntc'              : {'varname':            'TENDCT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convection'}, 
    'tntcas'            : {'varname':          'TENDTCAS', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Dry Convective Adjustment'}, 
    'tntcs'             : {'varname':           'TENDTCS', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Eddies'}, 
    'tntd'              : {'varname':            'TENDMT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Other Processes'}, 
    'tntfccql'          : {'varname':        'TENDTFCCQL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Liquid Precipitation Generation'}, 
    'tntfccqn'          : {'varname':        'TENDTFCCQN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Solid Precipitation Generation'}, 
    'tntfcsql'          : {'varname':        'TENDTFCSQL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Liquid Precipitation Generation'}, 
    'tntfcsqn'          : {'varname':        'TENDTFCSQN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Solid Precipitation Generation'}, 
    'tntfecl'           : {'varname':         'TENDTFECL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Liquid Precipitation Evaporation'}, 
    'tntfecn'           : {'varname':         'TENDTFECN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Solid Precipitation Evaporation'}, 
    'tntfesl'           : {'varname':         'TENDTFESL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Liquid Precipitation Evaporation'}, 
    'tntfesn'           : {'varname':         'TENDTFESN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Solid Precipitation Evaporation'}, 
    'tntfhimcc'         : {'varname':       'TENDTFHIMCC', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Melting/Icing'}, 
    'tntfplcl'          : {'varname':        'TENDTFPLCL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Liquid Precipitation'}, 
    'tntfplcn'          : {'varname':        'TENDTFPLCN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Convective Solid Precipitation'}, 
    'tntfplsl'          : {'varname':        'TENDTFPLSL', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Liquid Precipitation'}, 
    'tntfplsn'          : {'varname':        'TENDTFPLSN', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Stratiform Solid Precipitation'}, 
    'tnthc'             : {'varname':           'TENDCTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Convection'}, 
    'tnthd'             : {'varname':           'TENDMTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Other Processes'}, 
    'tnthl'             : {'varname':        'TENDTHETAL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Physics'}, 
    'tnthlc'            : {'varname':          'TENDCTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Convection'}, 
    'tnthld'            : {'varname':          'TENDMTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Other Processes'}, 
    'tnthllscp'         : {'varname':          'TENDSTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Large-scale Condensation and Precipitation'}, 
    'tnthlpbl'          : {'varname':          'TENDTTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Turbulence'}, 
    'tnthlrlw'          : {'varname':         'TENDLWTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to LW Radiation'}, 
    'tnthlrlwcs'        : {'varname':       'TENDLWTHLCS', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Clear-sky LW Radiation'}, 
    'tnthlrsw'          : {'varname':         'TENDSWTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to SW Radiation'}, 
    'tnthlrswcs'        : {'varname':       'TENDSWTHLCS', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Clear-sky SW Radiation'}, 
    'tnthlscp'          : {'varname':           'TENDSTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Large-scale Condensation and Precipitation'}, 
    'tnthlshc'          : {'varname':        'TENDSHCTHL', 'units':               'K/s', 'coef':         1, 'name':'Liquid Potential Temperature Tendency due to Shallow Convection'}, 
    'tnthpbl'           : {'varname':           'TENDTTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Turbulence'}, 
    'tnthrlw'           : {'varname':          'TENDLWTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to LW Radiation'}, 
    'tnthrlwcs'         : {'varname':        'TENDLWTHCS', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Clear-sky LW Radiation'}, 
    'tnthrsw'           : {'varname':          'TENDSWTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to SW Radiation'}, 
    'tnthrswcs'         : {'varname':        'TENDSWTHCS', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Clear-sky SW Radiation'}, 
    'tnthshc'           : {'varname':         'TENDSHCTH', 'units':               'K/s', 'coef':         1, 'name':'Potential Temperature Tendency due to Shallow Convection'}, 
    'tntlscp'           : {'varname':            'TENDST', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Large-scale Condensation and Precipitation'}, 
    'tntpbl'            : {'varname':            'TENDTT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Turbulence'}, 
    'tntrlw'            : {'varname':           'TENDLWT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to LW Radiation'}, 
    'tntrlwcs'          : {'varname':         'TENDLWTCS', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Clear-sky LW Radiation'}, 
    'tntrsw'            : {'varname':           'TENDSWT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to SW Radiation'}, 
    'tntrswcs'          : {'varname':         'TENDSWTCS', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Clear-sky SW Radiation'}, 
    'tntshc'            : {'varname':          'TENDSHCT', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Shallow Convection'}, 
    'tnuc'              : {'varname':            'TENDCU', 'units':              'm/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to Convection'}, 
    'tnud'              : {'varname':            'TENDMU', 'units':              'm/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to Other Processes'}, 
    'tnupbl'            : {'varname':            'TENDTU', 'units':              'm/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to Turbulence'}, 
    'tnushc'            : {'varname':          'TENDSHCU', 'units':              'm/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to Shallow Convection'}, 
    'tnvc'              : {'varname':            'TENDCV', 'units':              'm/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to Convection'}, 
    'tnvd'              : {'varname':            'TENDMV', 'units':              'm/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to Other Processes'}, 
    'tnvpbl'            : {'varname':            'TENDTV', 'units':              'm/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to Turbulence'}, 
    'tnvshc'            : {'varname':          'TENDSHCV', 'units':              'm/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to Shallow Convection'}, 
# 9. Physics fluxes
    'wpqp_conv'         : {'varname':           'WPQP_CV', 'units':     'kg kg-1 m s-1', 'coef':         1, 'name':'Water Vapor Water Flux due to Convection'}, 
    'wpqp_pbl'          : {'varname':           'WPQP_TU', 'units':     'kg kg-1 m s-1', 'coef':         1, 'name':'Water Vapor Water Flux due to Turbulence'}, 
    'wpqtp_conv'        : {'varname':         'ZWPQT_dee', 'units':     'kg kg-1 m s-1', 'coef':         1, 'name':'Total Water flux due to Convection'}, 
    'wpqtp_pbl'         : {'varname':         'ZWPQT_tur', 'units':     'kg kg-1 m s-1', 'coef':         1, 'name':'Total Water Flux due to Turbulence'}, 
    'wpthlp_conv'       : {'varname':          'WTHL_dee', 'units':           'K m s-1', 'coef':         1, 'name':'Liquid Potential Temperature Flux due to Convection'}, 
    'wpthlp_pbl'        : {'varname':          'WTHL_tur', 'units':           'K m s-1', 'coef':         1, 'name':'Liquid Potential Temperature Flux due to Turbulence'}, 
    'wpthp_conv'        : {'varname':          'WPTHP_CV', 'units':           'K m s-1', 'coef':         1, 'name':'Potential Temperature Flux due to Convection'}, 
    'wpthp_pbl'         : {'varname':          'WPTHP_TU', 'units':           'K m s-1', 'coef':         1, 'name':'Potential Temperature Flux due to Turbulence'}, 
    'wpup_conv'         : {'varname':           'WPUP_CV', 'units':            'm2 s-2', 'coef':         1, 'name':'Zonal Wind Flux due to Convection'}, 
    'wpup_pbl'          : {'varname':           'WPUP_TU', 'units':            'm2 s-2', 'coef':         1, 'name':'Zonal Wind Flux due to Turbulence'}, 
    'wpvp_conv'         : {'varname':           'WPVP_CV', 'units':            'm2 s-2', 'coef':         1, 'name':'Meridional Wind Flux due to Convection'}, 
    'wpvp_pbl'          : {'varname':           'WPVP_TU', 'units':            'm2 s-2', 'coef':         1, 'name':'Meridional Wind Flux due to Turbulenve'}, 
# 10. Forcing tendencies
    'tnqvadv'           : {'varname':           'ZFQ_ADV', 'units':                '??', 'coef':       1.0, 'name':'ZFQ_ADV'}, 
    'tnqvnudg'          : {'varname':          'ZFQ_NUDG', 'units':           'kg/kg/s', 'coef':         1, 'name':'Specific Humidity Tendency due to Nudging'}, 
    'tntadv'            : {'varname':           'ZFT_ADV', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Horizontal Advection'}, 
    'tntnudg'           : {'varname':          'ZFT_NUDG', 'units':               'K/s', 'coef':         1, 'name':'Temperature Tendency due to Nudging'}, 
    'tnugeo'            : {'varname':            'ZFUGEO', 'units':              'm/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to Geostrophic Adjustment'}, 
    'tnunudg'           : {'varname':          'ZFU_NUDG', 'units':              'm/s2', 'coef':         1, 'name':'Zonal wind Tendency due to Nudging'}, 
    'tnvgeo'            : {'varname':            'ZFVGEO', 'units':              'm/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to Geostrophic Adjustment'}, 
    'tnvnudg'           : {'varname':          'ZFV_NUDG', 'units':              'm/s2', 'coef':         1, 'name':'Meridional wind Tendency due to Nudging'}, 
# 11. Water and energy budget
    'RDMSE'             : {'varname':             'RDMSE', 'units':                 '-', 'coef':         1, 'name':'RDMSE'}, 
    'RMSE0'             : {'varname':             'RMSE0', 'units':                 '-', 'coef':         1, 'name':'RMSE0'}, 
    'RMSE1'             : {'varname':             'RMSE1', 'units':                 '-', 'coef':         1, 'name':'RMSE1'}, 
    'RMSE9'             : {'varname':             'RMSE9', 'units':                 '-', 'coef':         1, 'name':'RMSE9'}, 
    'denergy'           : {'varname':          'RDENERGY', 'units':              'J/kg', 'coef':         1, 'name':'RDENERGY'}, 
    'dwater'            : {'varname':           'RDWATER', 'units':             'kg/m2', 'coef':         1, 'name':'RDWATER'}, 
    'efluxSfc'          : {'varname':          'EFLUXSFC', 'units':              'W/m2', 'coef':         1, 'name':'Net Enthalpy Flux at Surface'}, 
    'efluxSfcAdj'       : {'varname':       'EFLUXSFCCAS', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to dry adjustment'}, 
    'efluxSfcConv'      : {'varname':        'EFLUXSFCCS', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to convective eddies'}, 
    'efluxSfcPrLat'     : {'varname':         'EFLUXSFC2', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to latent heat of precipitation'}, 
    'efluxSfcPrSen'     : {'varname':         'EFLUXSFC1', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to sensible heat of precipitation'}, 
    'efluxSfcRad'       : {'varname':       'EFLUXSFCRAD', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to radiation'}, 
    'efluxSfcTurb'      : {'varname':        'EFLUXSFCTS', 'units':              'W/m2', 'coef':         1, 'name':'Surface Enthalpy Flux due to turbulence'}, 
    'efluxTOA'          : {'varname':          'EFLUXTOA', 'units':              'W/m2', 'coef':         1, 'name':'Net Enthalpy Flux at TOA'}, 
    'iEadv'             : {'varname':       'TOTFORCEADV', 'units':              'W/m2', 'coef':         1, 'name':'Horizontal Advection of enthalpy integrated over the atmospheric column'}, 
    'iEnud'             : {'varname':       'TOTFORCENUD', 'units':              'W/m2', 'coef':         1, 'name':'Enthalpy Tendency due to nudging integrated over the atmospheric column'}, 
    'iEw'               : {'varname':           'ENERGYW', 'units':              'W/m2', 'coef':         1, 'name':'Vertical Advection of enthalpy integrated over the atmospheric column'}, 
    'iMSEadv'           : {'varname':            'MSEADV', 'units':              'W/m2', 'coef':         1, 'name':'Horizontal Advection of moist static energy integrated over the atmospheric column'}, 
    'iMSEnud'           : {'varname':            'MSENUD', 'units':              'W/m2', 'coef':         1, 'name':'Moist Static Energy Tendency due to nudging integrated over the atmospheric column'}, 
    'iQadv'             : {'varname':       'TOTFORCQADV', 'units':           'kg/m2/s', 'coef':         1, 'name':'Horizontal Advection of moisture integrated over the atmospheric column'}, 
    'iQnud'             : {'varname':       'TOTFORCQNUD', 'units':           'kg/m2/s', 'coef':         1, 'name':'Moisture Tendency due to nudging integrated over the atmospheric column'}, 
    'iQw'               : {'varname':            'WATERW', 'units':           'kg/m2/s', 'coef':         1, 'name':'Vertical Advection of specific humidity integrated over the atmospheric column'}, 
    'iTadv'             : {'varname':       'TOTFORCTADV', 'units':         'K kg/m2/s', 'coef':         1, 'name':'Horizontal Advection of temperature integrated over the atmospheric column'}, 
    'iTnud'             : {'varname':       'TOTFORCTNUD', 'units':         'K kg/m2/s', 'coef':         1, 'name':'Temperature Tendency due to nudging integrated over the atmospheric column'}, 
    'iUadv'             : {'varname':       'TOTFORCUADV', 'units':             'm2/s2', 'coef':         1, 'name':'Horizontal Advection of zonal wind integrated over the atmospheric column'}, 
    'iUnud'             : {'varname':       'TOTFORCUNUD', 'units':             'm2/s2', 'coef':         1, 'name':'Zonal Wind Tendency due to nudging integrated over the atmospheric column'}, 
    'iVadv'             : {'varname':       'TOTFORCVADV', 'units':             'm2/s2', 'coef':         1, 'name':'Horizontal Advection of meridional wind integrated over the atmospheric column'}, 
    'iVnud'             : {'varname':       'TOTFORCVNUD', 'units':             'm2/s2', 'coef':         1, 'name':'Meridional Wind Tendency due to nudging integrated over the atmospheric column'}, 
    'msefluxSfc'        : {'varname':        'MSEFLUXSFC', 'units':              'W/m2', 'coef':         1, 'name':'Net Moist Static Energy Flux at Surface'}, 
    'qflux'             : {'varname':         'WATERFLUX', 'units':           'kg/m2/s', 'coef':         1, 'name':'Net Flux of water in the atmosphere'}, 
    'qfluxEv'           : {'varname':        'WATERFLUXE', 'units':           'kg/m2/s', 'coef':         1, 'name':'Net Flux of water at Surface due to Evaporation'}, 
    'qfluxPr'           : {'varname':        'WATERFLUXP', 'units':           'kg/m2/s', 'coef':         1, 'name':'Net Flux of water at Surface due to Precipitation'}, 
# 12. Gaseous variables
    'rCCL4'             : {'varname':              'ZCL4', 'units':             'kg/kg', 'coef':         1, 'name':'CCL4 Mixing Ratio'}, 
    'rCFC11'            : {'varname':              'ZC11', 'units':             'kg/kg', 'coef':         1, 'name':'CFC11 Mixing Ratio'}, 
    'rCFC12'            : {'varname':              'ZC12', 'units':             'kg/kg', 'coef':         1, 'name':'CFC12 Mixing Ratio'}, 
    'rCFC22'            : {'varname':              'ZC22', 'units':             'kg/kg', 'coef':         1, 'name':'CFC22 Mixing Ratio'}, 
    'rCH4'              : {'varname':              'ZCH4', 'units':             'kg/kg', 'coef':         1, 'name':'CH4 Mixing Ratio'}, 
    'rCO2'              : {'varname':              'ZCO2', 'units':             'kg/kg', 'coef':         1, 'name':'CO2 Mixing Ratio'}, 
    'rN2O'              : {'varname':              'ZN2O', 'units':             'kg/kg', 'coef':         1, 'name':'N2O Mixing Ratio'}, 
    'rNO2'              : {'varname':              'ZNO2', 'units':             'kg/kg', 'coef':         1, 'name':'NO2 Mixing Ratio'}, 
    'rO3'               : {'varname':              'ZOZN', 'units':             'kg/kg', 'coef':         1, 'name':'O3 Mixing Ratio'}, 
# 13. Convective variables
    'B_up'              : {'varname':              'B_UP', 'units':             'm s-2', 'coef':         1, 'name':'Updraft_Buoyancy'}, 
    'Mf'                : {'varname':                'MF', 'units':        'kg m-2 s-1', 'coef':         1, 'name':'Convective Mass Flux'}, 
    'T_up'              : {'varname':               'PTU', 'units':                 'K', 'coef':         1, 'name':'Convective Updraft Temperature'}, 
    'Thu'               : {'varname':              'ZTHN', 'units':                 'K', 'coef':         1, 'name':'Updraft Potential Temperature'}, 
    'Tu'                : {'varname':               'ZTN', 'units':                 'K', 'coef':         1, 'name':'Updraft Temperature'}, 
    'ZINTEGMAX'         : {'varname':         'ZINTEGMAX', 'units':                 '-', 'coef':         1, 'name':'ZINTEGMAX'}, 
    'ZKMAX'             : {'varname':             'ZKMAX', 'units':                 '-', 'coef':         1, 'name':'ZKMAX'}, 
    'ZMMAX'             : {'varname':             'ZMMAX', 'units':                 '-', 'coef':         1, 'name':'ZMMAX'}, 
    'ZS15'              : {'varname':              'ZS15', 'units':                 '-', 'coef':         1, 'name':'ZS15'}, 
    'ZS16'              : {'varname':              'ZS16', 'units':                 '-', 'coef':         1, 'name':'ZS16'}, 
    'ZTAU'              : {'varname':              'ZTAU', 'units':                 '-', 'coef':         1, 'name':'ZTAU'}, 
    'ZWMAX'             : {'varname':             'ZWMAX', 'units':                 '-', 'coef':         1, 'name':'ZWMAX'}, 
    'ZZMAX'             : {'varname':             'ZZMAX', 'units':                 '-', 'coef':         1, 'name':'ZZMAX'}, 
    'aipcmt'            : {'varname':            'AIPCMT', 'units':                 '-', 'coef':         1, 'name':'Activity index of PCMT'}, 
    'alpha'             : {'varname':              'ZALF', 'units':                 '-', 'coef':         1, 'name':'Closure coefficient'}, 
    'alpha_dn'          : {'varname':             'PDDAL', 'units':                 '-', 'coef':         1, 'name':'Convective Downdraft Fraction'}, 
    'alpha_up'          : {'varname':             'PUDAL', 'units':                 '-', 'coef':         1, 'name':'Convective Updraft Fraction'}, 
    'buoy'              : {'varname':            'ZBUO_W', 'units':             'm s-2', 'coef':         1, 'name':'Convection Buoyancy used in Updraft Vertical Velocity Budget'}, 
    'cape'              : {'varname':             'PCAPE', 'units':              'J/kg', 'coef':         1, 'name':'CAPE'}, 
    'dTv_up'            : {'varname':        'TVUD-TVENV', 'units':                 'K', 'coef':         1, 'name':'Tv_updraft-Tv_env'}, 
    'det_u'             : {'varname':           'ZDETR_U', 'units':               's-1', 'coef':         1, 'name':'Convective Updraft Detrainment'}, 
    'dw_Kd'             : {'varname':         'BILOM+TKD', 'units':            'Pa s-2', 'coef':         1, 'name':'Updraft Vertical Velocity Tendency due to Aerodynamic Drag'}, 
    'dw_buoy'           : {'varname':       'BILOM+TBUOY', 'units':            'Pa s-2', 'coef':         1, 'name':'Updraft Vertical Velocity Tendency due to Vertical Buoyancy'}, 
    'dw_entr'           : {'varname':       'BILOM+TENTR', 'units':            'Pa s-2', 'coef':         1, 'name':'Updraft Vertical Velocity Tendency due to Entrainment'}, 
    'dw_fric'           : {'varname':       'BILOM+TFRIC', 'units':            'Pa s-2', 'coef':         1, 'name':'Updraft Vertical Velocity Tendency due to Friction'}, 
    'dw_transp'         : {'varname':     'BILOM+TTRANSP', 'units':            'Pa s-2', 'coef':         1, 'name':'Updraft Vertical Velocity Tendency due to Vertical Transport'}, 
    'entr_u'            : {'varname':           'ZENTR_U', 'units':               's-1', 'coef':         1, 'name':'Convective Updraft Entrainment'}, 
    'eps_u'             : {'varname':        'ZEPSILON_U', 'units':               'm-1', 'coef':         1, 'name':'Fractional Convective Updraft Entrainment'}, 
    'eps_u_org'         : {'varname':          'ZEPS_ORG', 'units':               'm-1', 'coef':         1, 'name':'Fractional Organised Convective Updraft Entrainment'}, 
    'eps_u_tur'         : {'varname':          'ZEPS_TUR', 'units':               'm-1', 'coef':         1, 'name':'Fractional Turbulent Convective Updraft Entrainment'}, 
    'knlab'             : {'varname':             'KNLAB', 'units':                 '-', 'coef':         1, 'name':'KNLAB'}, 
    'knnd'              : {'varname':              'KNND', 'units':                 '-', 'coef':         1, 'name':'KNND'}, 
    'omega_dn'          : {'varname':             'PDDOM', 'units':              'Pa/s', 'coef':         1, 'name':'Convective Downdraft Pressure Velocity'}, 
    'omega_ref'         : {'varname':            'ZVVREF', 'units':              'Pa/s', 'coef':         1, 'name':'Reference Vertical Velocity'}, 
    'omega_up'          : {'varname':             'PUDOM', 'units':              'Pa/s', 'coef':         1, 'name':'Convective Updraft Pressure Velocity'}, 
    'qcu'               : {'varname':               'ZLN', 'units':             'kg/kg', 'coef':         1, 'name':'Updraft Condensed Water'}, 
    'qv_up'             : {'varname':               'PQU', 'units':             'kg/kg', 'coef':         1, 'name':'Convective Updraft Specific Humidity'}, 
    'qvu'               : {'varname':               'ZQN', 'units':             'kg/kg', 'coef':         1, 'name':'Updraft Specific Humidity'}, 
    'w_dn'              : {'varname':              'ZDDW', 'units':               'm/s', 'coef':         1, 'name':'Convective Downdraft Velocity'}, 
    'w_up'              : {'varname':               'ZWU', 'units':               'm/s', 'coef':         1, 'name':'Convective Updraft Velocity'}, 
    'w_up_bud'          : {'varname':             'BILOM', 'units':            'Pa s-1', 'coef':         1, 'name':'Updraft Vertical Velocity used in Budget Equation'}, 
# 14. Wake variables
    'Cstar'             : {'varname':        'PWAKECSTAR', 'units':               'm/s', 'coef':         1, 'name':'Wake spreading velocity'}, 
    'Mf_dn'             : {'varname':             'ZMDWN', 'units':           'kg/m2/s', 'coef':         1, 'name':'Downdraft Mass flux'}, 
    'Mf_up'             : {'varname':              'ZMUP', 'units':           'kg/m2/s', 'coef':         1, 'name':'Updraft Mass flux'}, 
    'Tw_undi'           : {'varname':           'ZTWUNDI', 'units':                 'K', 'coef':         1, 'name':'Wet-bulb Temperature in undisturbed area'}, 
    'Tw_wake'           : {'varname':           'ZTWWAKE', 'units':                 'K', 'coef':         1, 'name':'Wet-bulb Temperature in wake'}, 
    'ZCWAKE'            : {'varname':            'ZCWAKE', 'units':                 '-', 'coef':         1, 'name':'ZCWAKE'}, 
    'ZMWAKE'            : {'varname':            'ZMWAKE', 'units':           'kg/m2/s', 'coef':         1, 'name':'ZMWAKE'}, 
    'ZS12'              : {'varname':              'ZS12', 'units':                'Pa', 'coef':         1, 'name':'ZS12'}, 
    'd_delta_q'         : {'varname':      'PWAKEDDELTAQ', 'units':           'kg/kg/s', 'coef':         1, 'name':'delta q tendency'}, 
    'd_delta_t'         : {'varname':      'PWAKEDDELTAT', 'units':               'K/s', 'coef':         1, 'name':'delta T tendency'}, 
    'd_delta_t_gw'      : {'varname':    'PWAKEDDELTATGW', 'units':               'K/s', 'coef':         1, 'name':' delta T tendency due to GW'}, 
    'delta_q'           : {'varname':       'PWAKEDELTAQ', 'units':             'kg/kg', 'coef':         1, 'name':'delta q'}, 
    'delta_t'           : {'varname':       'PWAKEDELTAT', 'units':                 'K', 'coef':         1, 'name':'delta T'}, 
    'delta_th'          : {'varname':          'PWAKEDTH', 'units':                 'K', 'coef':         1, 'name':'Potential Temperature Difference'}, 
    'dp_delt_omg'       : {'varname':    'PWAKEDPDELTOMG', 'units':                '/s', 'coef':         1, 'name':'vertical gradient of wake_omg'}, 
    'dq_KE'             : {'varname':         'PWAKEDQKE', 'units':           'kg/kg/s', 'coef':         1, 'name':'differential moistening (wake-unperturbed) CONV'}, 
    'dq_PBL'            : {'varname':        'PWAKEDQPBL', 'units':           'kg/kg/S', 'coef':         1, 'name':'differential moistening (wake-unperturbed) PBL'}, 
    'dq_dn'             : {'varname':            'ZDQDWN', 'units':           'kg/kg/s', 'coef':         1, 'name':'qv tendendy due to downdrafts'}, 
    'dq_up'             : {'varname':              'ZDQA', 'units':           'kg/kg/s', 'coef':         1, 'name':'qv tendency due to updrafts'}, 
    'dq_wake'           : {'varname':           'PDQWAKE', 'units':               'K_s', 'coef':         1, 'name':'q tendency due to wake'}, 
    'dq_wake2'          : {'varname':         'TENDWAKEQ', 'units':               'K_s', 'coef':         1, 'name':'q tendency due to wake (cptend_new)'}, 
    'dt_KE'             : {'varname':         'PWAKEDTKE', 'units':               'K/s', 'coef':         1, 'name':'differential heating (wake-unperturbed) CONV'}, 
    'dt_PBL'            : {'varname':        'PWAKEDTPBL', 'units':               'K/s', 'coef':         1, 'name':'differential heating (wake-unperturbed) PBL'}, 
    'dt_dn'             : {'varname':            'ZDTDWN', 'units':               'K/s', 'coef':         1, 'name':'T tendendy due to downdrafts'}, 
    'dt_up'             : {'varname':              'ZDTA', 'units':               'K/s', 'coef':         1, 'name':'T tendency due to updrafts'}, 
    'dt_wake'           : {'varname':           'PDTWAKE', 'units':               'K/s', 'coef':         1, 'name':'T tendency due to wake'}, 
    'dt_wake2'          : {'varname':         'TENDWAKET', 'units':               'K/s', 'coef':         1, 'name':'T tendency due to wake (cptend_new)'}, 
    'hw'                : {'varname':            'PWAKEH', 'units':                 'm', 'coef':         1, 'name':'Wake depth'}, 
    'omg_w'             : {'varname':          'PWAKEOMG', 'units':              'Pa/s', 'coef':         1, 'name':'Wake verticale velocity'}, 
    'omgb'              : {'varname':             'POMGB', 'units':              'Pa/s', 'coef':         1, 'name':'LS Vertical Velocity'}, 
    'omgb'              : {'varname':             'POMGB', 'units':              'Pa/s', 'coef':         1, 'name':'LS Vertical Velocity'}, 
    'omgb_dth'          : {'varname':      'PWAKEOMGBDTH', 'units':               'K/s', 'coef':         1, 'name':'flux of delta_theta transported by LS omega'}, 
    'q_undi'            : {'varname':            'PQUNDI', 'units':             'kg/kg', 'coef':         1, 'name':'Specific humidity in unperturbed area'}, 
    'q_undi_pcmt'       : {'varname':            'ZQUNDI', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Humidity in undisturbed area (PCMT)'}, 
    'q_wake_pcmt'       : {'varname':            'ZQWAKE', 'units':             'kg/kg', 'coef':         1, 'name':'Specific Humidity in wake (PCMT)'}, 
    'qsat_undi'         : {'varname':         'ZQSATUNDI', 'units':             'kg/kg', 'coef':         1, 'name':'Saturation Specific Humidity in undisturbed area'}, 
    'qsat_wake'         : {'varname':         'ZQSATWAKE', 'units':             'kg/kg', 'coef':         1, 'name':'Saturation Specific Humidity in wake'}, 
    'qw_undi'           : {'varname':           'ZQWUNDI', 'units':             'kg/kg', 'coef':         1, 'name':'Wet-bulb Specific Humidity in undisturbed area'}, 
    'qw_wake'           : {'varname':           'ZQWWAKE', 'units':             'kg/kg', 'coef':         1, 'name':'Wet-bulb Specific Humidity in wake'}, 
    'sigd'              : {'varname':             'ZSIGD', 'units':                 '-', 'coef':         1, 'name':'Downdraft area fraction'}, 
    'sigmaw'            : {'varname':            'PWAKES', 'units':                 '-', 'coef':         1, 'name':'wake fractional area'}, 
    'spread_w'          : {'varname':       'PWAKESPREAD', 'units':               'K/s', 'coef':         1, 'name':'Spreading term in wake_delt'}, 
    't_undi'            : {'varname':            'PTUNDI', 'units':                 'K', 'coef':         1, 'name':'Temperature in unperturbed area'}, 
    't_undi_pcmt'       : {'varname':            'ZTUNDI', 'units':                 'K', 'coef':         1, 'name':'Temperature in undisturbed area (PCMT)'}, 
    't_wake_pcmt'       : {'varname':            'ZTWAKE', 'units':                 'K', 'coef':         1, 'name':'Temperature in wake (PCMT)'}, 
    'wake_fip'          : {'varname':          'PWAKEFIP', 'units':              'W/m2', 'coef':         1, 'name':'wake ALP'}, 
    'wake_gfl'          : {'varname':          'PWAKEGFL', 'units':                 'm', 'coef':         1, 'name':'Wake Gust Front Length'}, 
    'wake_pe'           : {'varname':           'PWAKEPE', 'units':              'J/kg', 'coef':         1, 'name':'Wake Potential Energy (WAPE)'}, 
    'wdens'             : {'varname':         'PWAKEDENS', 'units':               '/m2', 'coef':         1, 'name':'Wake density'}, 
# 15. Turbulence variables
    'ECT0'              : {'varname':              'ECT0', 'units':                 '-', 'coef':         1, 'name':'ECT0'}, 
    'ECT1'              : {'varname':              'ECT1', 'units':                 '-', 'coef':         1, 'name':'ECT1'}, 
    'KU'                : {'varname':                'KU', 'units':                 '-', 'coef':         1, 'name':'KU'}, 
    'LMECT'             : {'varname':             'LMECT', 'units':                 '-', 'coef':         1, 'name':'LMECT'}, 
    'PECTCLS'           : {'varname':           'PECTCLS', 'units':                 '-', 'coef':         1, 'name':'PECTCLS'}, 
    'PKCLS'             : {'varname':             'PKCLS', 'units':                 '-', 'coef':         1, 'name':'PKCLS'}, 
    'PKUROV'            : {'varname':            'PKUROV', 'units':                 '-', 'coef':         1, 'name':'PKUROV'}, 
    'PPRODTH'           : {'varname':           'PPRODTH', 'units':                 '-', 'coef':         1, 'name':'PPRODTH'}, 
    'PUSLE'             : {'varname':             'PUSLE', 'units':                 '-', 'coef':         1, 'name':'PUSLE'}, 
    'Q11'               : {'varname':              'ZQ11', 'units':                 '-', 'coef':         1, 'name':'Normalized saturation deficit'}, 
    'Q11max'            : {'varname':            'ZQ1MAX', 'units':                 '-', 'coef':         1, 'name':'Maximum Normalized saturation deficit'}, 
    'Q11min'            : {'varname':            'ZQ1MIN', 'units':                 '-', 'coef':         1, 'name':'Minimum Normalized saturation deficit'}, 
    'TKEDIF'            : {'varname':            'TKEDIF', 'units':                 '-', 'coef':         1, 'name':'TKEDIF'}, 
    'TKEDISS'           : {'varname':           'TKEDISS', 'units':                 '-', 'coef':         1, 'name':'TKEDISS'}, 
    'TKEPRDY'           : {'varname':           'TKEPRDY', 'units':                 '-', 'coef':         1, 'name':'TKEPRDY'}, 
    'TKEPRTH'           : {'varname':           'TKEPRTH', 'units':                 '-', 'coef':         1, 'name':'TKEPRTH'}, 
    'TKETEND'           : {'varname':           'TKETEND', 'units':                 '-', 'coef':         1, 'name':'TKETEND'}, 
    'TNECT_BUO'         : {'varname':         'TNECT_BUO', 'units':                 '-', 'coef':         1, 'name':'TNECT_BUO'}, 
    'TNECT_DIF'         : {'varname':         'TNECT_DIF', 'units':                 '-', 'coef':         1, 'name':'TNECT_DIF'}, 
    'TNECT_DIS'         : {'varname':         'TNECT_DIS', 'units':                 '-', 'coef':         1, 'name':'TNECT_DIS'}, 
    'TNECT_DYN'         : {'varname':         'TNECT_DYN', 'units':                 '-', 'coef':         1, 'name':'TNECT_DYN'}, 
    'acoef'             : {'varname':               'ZAA', 'units':                 '-', 'coef':         1, 'name':'a Coefficient'}, 
    'igs'               : {'varname':            'ZIGMAS', 'units':             'kg/kg', 'coef':         1, 'name':'Subgrid Standard Deviation of s'}, 
    'igs2'              : {'varname':           'ZIGMAS2', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Subgrid Variance of s'}, 
    'igs2conv'          : {'varname':       'ZIGMAS2CONV', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Convective Subgrid Variance of s'}, 
    'igs2turb'          : {'varname':       'ZIGMAS2TURB', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Turbulent Subgrid Variance of s'}, 
    'mlen'              : {'varname':             'ZZLMF', 'units':            'm2 s-2', 'coef':         1, 'name':'Mixing Length*g'}, 
    'sigc0'             : {'varname':        'PSIGCLOUD0', 'units':             'kg/kg', 'coef':         1, 'name':'PSIGCLOUD0'}, 
    'sigc1'             : {'varname':        'PSIGCLOUD1', 'units':             'kg/kg', 'coef':         1, 'name':'PSIGCLOUD1'}, 
    'sigs'              : {'varname':           'ZSIGMAS', 'units':             'kg/kg', 'coef':         1, 'name':'Subgrid Standard Deviation of s (LNEBECT)'}, 
    'sigs2'             : {'varname':          'ZSIGMAS2', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Subgrid Variance of s (LNEBECT)'}, 
    'sigs2conv'         : {'varname':      'ZSIGMAS2CONV', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Convective Subgrid Variance of s (LNEBECT)'}, 
    'sigs2turb'         : {'varname':      'ZSIGMAS2TURB', 'units':         '(kg/kg)^2', 'coef':         1, 'name':'Turbulent Subgrid Variance of s (LNEBECT)'}, 
# 16. COSP variables
    'albisccp'          : {'varname':          'albisccp', 'units':                 '1', 'coef':         1, 'name':'albisccp'}, 
    'atb532'            : {'varname':            'atb532', 'units':          'm-1 sr-1', 'coef':         1, 'name':'atb532'}, 
    'boxptopisccp'      : {'varname':      'boxptopisccp', 'units':                'Pa', 'coef':         1, 'name':'boxptopisccp'}, 
    'boxtauisccp'       : {'varname':       'boxtauisccp', 'units':                 '1', 'coef':         1, 'name':'boxtauisccp'}, 
    'cfadDbze94'        : {'varname':        'cfadDbze94', 'units':                 '1', 'coef':         1, 'name':'cfadDbze94'}, 
    'cfadLidarsr532'    : {'varname':    'cfadLidarsr532', 'units':                 '1', 'coef':         1, 'name':'cfadLidarsr532'}, 
    'clMISR'            : {'varname':            'clMISR', 'units':                 '%', 'coef':         1, 'name':'clMISR'}, 
    'clcalipso'         : {'varname':         'clcalipso', 'units':                 '%', 'coef':         1, 'name':'clcalipso'}, 
    'clcalipso'         : {'varname':         'clcalipso', 'units':                 '%', 'coef':         1, 'name':'clcalipso'}, 
    'clcalipso2'        : {'varname':        'clcalipso2', 'units':                 '%', 'coef':         1, 'name':'clcalipso2'}, 
    'clcalipsoice'      : {'varname':      'clcalipsoice', 'units':                 '%', 'coef':         1, 'name':'clcalipsoice'}, 
    'clcalipsoliq'      : {'varname':      'clcalipsoliq', 'units':                 '%', 'coef':         1, 'name':'clcalipsoliq'}, 
    'clcalipsotmp'      : {'varname':      'clcalipsotmp', 'units':                 '%', 'coef':         1, 'name':'clcalipsotmp'}, 
    'clcalipsotmpice'   : {'varname':   'clcalipsotmpice', 'units':                 '%', 'coef':         1, 'name':'clcalipsotmpice'}, 
    'clcalipsotmpliq'   : {'varname':   'clcalipsotmpliq', 'units':                 '%', 'coef':         1, 'name':'clcalipsotmpliq'}, 
    'clcalipsotmpun'    : {'varname':    'clcalipsotmpun', 'units':                 '%', 'coef':         1, 'name':'clcalipsotmpun'}, 
    'clcalipsoun'       : {'varname':       'clcalipsoun', 'units':                 '%', 'coef':         1, 'name':'clcalipsoun'}, 
    'clhcalipso'        : {'varname':        'clhcalipso', 'units':                 '%', 'coef':         1, 'name':'clhcalipso'}, 
    'clhcalipsoice'     : {'varname':     'clhcalipsoice', 'units':                 '%', 'coef':         1, 'name':'clhcalipsoice'}, 
    'clhcalipsoliq'     : {'varname':     'clhcalipsoliq', 'units':                 '%', 'coef':         1, 'name':'clhcalipsoliq'}, 
    'clhcalipsoun'      : {'varname':      'clhcalipsoun', 'units':                 '%', 'coef':         1, 'name':'clhcalipsoun'}, 
    'clhmodis'          : {'varname':          'clhmodis', 'units':                 '%', 'coef':         1, 'name':'clhmodis'}, 
    'climodis'          : {'varname':          'climodis', 'units':                 '%', 'coef':         1, 'name':'climodis'}, 
    'clisccp'           : {'varname':           'clisccp', 'units':                 '%', 'coef':         1, 'name':'clisccp'}, 
    'cllcalipso'        : {'varname':        'cllcalipso', 'units':                 '%', 'coef':         1, 'name':'cllcalipso'}, 
    'cllcalipsoice'     : {'varname':     'cllcalipsoice', 'units':                 '%', 'coef':         1, 'name':'cllcalipsoice'}, 
    'cllcalipsoliq'     : {'varname':     'cllcalipsoliq', 'units':                 '%', 'coef':         1, 'name':'cllcalipsoliq'}, 
    'cllcalipsoun'      : {'varname':      'cllcalipsoun', 'units':                 '%', 'coef':         1, 'name':'cllcalipsoun'}, 
    'cllmodis'          : {'varname':          'cllmodis', 'units':                 '%', 'coef':         1, 'name':'cllmodis'}, 
    'clmcalipso'        : {'varname':        'clmcalipso', 'units':                 '%', 'coef':         1, 'name':'clmcalipso'}, 
    'clmcalipsoice'     : {'varname':     'clmcalipsoice', 'units':                 '%', 'coef':         1, 'name':'clmcalipsoice'}, 
    'clmcalipsoliq'     : {'varname':     'clmcalipsoliq', 'units':                 '%', 'coef':         1, 'name':'clmcalipsoliq'}, 
    'clmcalipsoun'      : {'varname':      'clmcalipsoun', 'units':                 '%', 'coef':         1, 'name':'clmcalipsoun'}, 
    'clmmodis'          : {'varname':          'clmmodis', 'units':                 '%', 'coef':         1, 'name':'clmmodis'}, 
    'clmodis'           : {'varname':           'clmodis', 'units':                 '%', 'coef':         1, 'name':'clmodis'}, 
    'cltcalipso'        : {'varname':        'cltcalipso', 'units':                 '%', 'coef':         1, 'name':'cltcalipso'}, 
    'cltcalipsoice'     : {'varname':     'cltcalipsoice', 'units':                 '%', 'coef':         1, 'name':'cltcalipsoice'}, 
    'cltcalipsoliq'     : {'varname':     'cltcalipsoliq', 'units':                 '%', 'coef':         1, 'name':'cltcalipsoliq'}, 
    'cltcalipsoun'      : {'varname':      'cltcalipsoun', 'units':                 '%', 'coef':         1, 'name':'cltcalipsoun'}, 
    'cltisccp'          : {'varname':          'cltisccp', 'units':                 '%', 'coef':         1, 'name':'cltisccp'}, 
    'cltlidarradar'     : {'varname':     'cltlidarradar', 'units':                 '%', 'coef':         1, 'name':'cltlidarradar'}, 
    'cltmodis'          : {'varname':          'cltmodis', 'units':                 '%', 'coef':         1, 'name':'cltmodis'}, 
    'clwmodis'          : {'varname':          'clwmodis', 'units':                 '%', 'coef':         1, 'name':'clwmodis'}, 
    'dbze94'            : {'varname':            'dbze94', 'units':                 '1', 'coef':         1, 'name':'dbze94'}, 
    'iwpmodis'          : {'varname':          'iwpmodis', 'units':            'kg m-2', 'coef':         1, 'name':'iwpmodis'}, 
    'lidarBetaMol532'   : {'varname':   'lidarBetaMol532', 'units':          'm-1 sr-1', 'coef':         1, 'name':'lidarBetaMol532'}, 
    'lwpmodis'          : {'varname':          'lwpmodis', 'units':            'kg m-2', 'coef':         1, 'name':'lwpmodis'}, 
    'meantbclrisccp'    : {'varname':    'meantbclrisccp', 'units':                 'K', 'coef':         1, 'name':'meantbclrisccp'}, 
    'meantbisccp'       : {'varname':       'meantbisccp', 'units':                 'K', 'coef':         1, 'name':'meantbisccp'}, 
    'parasolRefl'       : {'varname':       'parasolRefl', 'units':                 '1', 'coef':         1, 'name':'parasolRefl'}, 
    'pctisccp'          : {'varname':          'pctisccp', 'units':                'Pa', 'coef':         1, 'name':'pctisccp'}, 
    'pctmodis'          : {'varname':          'pctmodis', 'units':                'Pa', 'coef':         1, 'name':'pctmodis'}, 
    'reffclimodis'      : {'varname':      'reffclimodis', 'units':                 'm', 'coef':         1, 'name':'reffclimodis'}, 
    'reffclwmodis'      : {'varname':      'reffclwmodis', 'units':                 'm', 'coef':         1, 'name':'reffclwmodis'}, 
    'tauilogmodis'      : {'varname':      'tauilogmodis', 'units':                 '1', 'coef':         1, 'name':'tauilogmodis'}, 
    'tauimodis'         : {'varname':         'tauimodis', 'units':                 '1', 'coef':         1, 'name':'tauimodis'}, 
    'tauisccp'          : {'varname':          'tauisccp', 'units':                 '1', 'coef':         1, 'name':'tauisccp'}, 
    'tautlogmodis'      : {'varname':      'tautlogmodis', 'units':                 '1', 'coef':         1, 'name':'tautlogmodis'}, 
    'tautmodis'         : {'varname':         'tautmodis', 'units':                 '1', 'coef':         1, 'name':'tautmodis'}, 
    'tauwlogmodis'      : {'varname':      'tauwlogmodis', 'units':                 '1', 'coef':         1, 'name':'tauwlogmodis'}, 
    'tauwmodis'         : {'varname':         'tauwmodis', 'units':                 '1', 'coef':         1, 'name':'tauwmodis'}, 
# 16.1 COSP input variables
    'PEMIS_COSP'        : {'varname':        'PEMIS_COSP', 'units':                 '-', 'coef':         1, 'name':'PEMIS_COSP'}, 
    'PLSM_COSP'         : {'varname':         'PLSM_COSP', 'units':                 '-', 'coef':         1, 'name':'PLSM_COSP'}, 
    'PMU0_COSP'         : {'varname':         'PMU0_COSP', 'units':                 '-', 'coef':         1, 'name':'PMU0_COSP'}, 
    'PTS_COSP'          : {'varname':          'PTS_COSP', 'units':                 '-', 'coef':         1, 'name':'PTS_COSP'}, 
    'ZAPHIF_COSP'       : {'varname':       'ZAPHIF_COSP', 'units':                 '-', 'coef':         1, 'name':'ZAPHIF_COSP'}, 
    'ZAPHI_COSP'        : {'varname':        'ZAPHI_COSP', 'units':                 '-', 'coef':         1, 'name':'ZAPHI_COSP'}, 
    'ZAPH_COSP'         : {'varname':         'ZAPH_COSP', 'units':                 '-', 'coef':         1, 'name':'ZAPH_COSP'}, 
    'ZAP_COSP'          : {'varname':          'ZAP_COSP', 'units':                 '-', 'coef':         1, 'name':'ZAP_COSP'}, 
    'ZCLFRCC_COSP'      : {'varname':      'ZCLFRCC_COSP', 'units':                 '-', 'coef':         1, 'name':'ZCLFRCC_COSP'}, 
    'ZCLFR_COSP'        : {'varname':        'ZCLFR_COSP', 'units':                 '-', 'coef':         1, 'name':'ZCLFR_COSP'}, 
    'ZEMILW_COSP'       : {'varname':       'ZEMILW_COSP', 'units':                 '-', 'coef':         1, 'name':'ZEMILW_COSP'}, 
    'ZFLCCRAIN_COSP'    : {'varname':    'ZFLCCRAIN_COSP', 'units':                 '-', 'coef':         1, 'name':'ZFLCCRAIN_COSP'}, 
    'ZFLCCSNOW_COSP'    : {'varname':    'ZFLCCSNOW_COSP', 'units':                 '-', 'coef':         1, 'name':'ZFLCCSNOW_COSP'}, 
    'ZFLLSRAIN_COSP'    : {'varname':    'ZFLLSRAIN_COSP', 'units':                 '-', 'coef':         1, 'name':'ZFLLSRAIN_COSP'}, 
    'ZFLLSSNOW_COSP'    : {'varname':    'ZFLLSSNOW_COSP', 'units':                 '-', 'coef':         1, 'name':'ZFLLSSNOW_COSP'}, 
    'ZLAT_COSP'         : {'varname':         'ZLAT_COSP', 'units':                 '-', 'coef':         1, 'name':'ZLAT_COSP'}, 
    'ZLON_COSP'         : {'varname':         'ZLON_COSP', 'units':                 '-', 'coef':         1, 'name':'ZLON_COSP'}, 
    'ZMRCCICE_COSP'     : {'varname':     'ZMRCCICE_COSP', 'units':                 '-', 'coef':         1, 'name':'ZMRCCICE_COSP'}, 
    'ZMRCCLIQ_COSP'     : {'varname':     'ZMRCCLIQ_COSP', 'units':                 '-', 'coef':         1, 'name':'ZMRCCLIQ_COSP'}, 
    'ZMRLSICE_COSP'     : {'varname':     'ZMRLSICE_COSP', 'units':                 '-', 'coef':         1, 'name':'ZMRLSICE_COSP'}, 
    'ZMRLSLIQ_COSP'     : {'varname':     'ZMRLSLIQ_COSP', 'units':                 '-', 'coef':         1, 'name':'ZMRLSLIQ_COSP'}, 
    'ZOZN_COSP'         : {'varname':         'ZOZN_COSP', 'units':                 '-', 'coef':         1, 'name':'ZOZN_COSP'}, 
    'ZQ_COSP'           : {'varname':           'ZQ_COSP', 'units':                 '-', 'coef':         1, 'name':'ZQ_COSP'}, 
    'ZRADIP_COSP'       : {'varname':       'ZRADIP_COSP', 'units':                 '-', 'coef':         1, 'name':'ZRADIP_COSP'}, 
    'ZRADLP_COSP'       : {'varname':       'ZRADLP_COSP', 'units':                 '-', 'coef':         1, 'name':'ZRADLP_COSP'}, 
    'ZRH_COSP'          : {'varname':          'ZRH_COSP', 'units':                 '-', 'coef':         1, 'name':'ZRH_COSP'}, 
    'ZTAUSW_COSP'       : {'varname':       'ZTAUSW_COSP', 'units':                 '-', 'coef':         1, 'name':'ZTAUSW_COSP'}, 
    'ZT_COSP'           : {'varname':           'ZT_COSP', 'units':                 '-', 'coef':         1, 'name':'ZT_COSP'}, 
    'ZU_COSP'           : {'varname':           'ZU_COSP', 'units':                 '-', 'coef':         1, 'name':'ZU_COSP'}, 
    'ZV_COSP'           : {'varname':           'ZV_COSP', 'units':                 '-', 'coef':         1, 'name':'ZV_COSP'}, 
# 17. Miscellanenous
    'Cp'                : {'varname':               'PCP', 'units':            'J/K/kg', 'coef':         1, 'name':'Heat Capacity of Air'}, 
    'Lv'                : {'varname':               'PLH', 'units':              'J/kg', 'coef':         1, 'name':'Latent Heat of Vaporization'},
# 18. ISBA variables
    'tas_isba'           : {'varname':            'tas_isba', 'units':              'K', 'coef':         1, 'name':'ISBA 2-m Temperature'}, 
    'huss_isba'          : {'varname':           'huss_isba', 'units':        'kg kg-1', 'coef':         1, 'name':'ISBA 2-m Specific Humidity'}, 
    'hurs_isba'          : {'varname':           'hurs_isba', 'units':              '-', 'coef':         1, 'name':'ISBA 2-m Relative Humidity'}, 
    'sfcWind_isba'       : {'varname':        'sfcWind_isba', 'units':          'm s-1', 'coef':         1, 'name':'ISBA 10-m Wind Speed'}, 
    'rsds_isba'          : {'varname':           'rsds_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Downwelling SW Radiation at surface'}, 
    'rsus_isba'          : {'varname':           'ruds_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Upwelling SW Radiation at surface'}, 
    'rss_isba'           : {'varname':            'rss_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Net SW Radiation at surface'}, 
    'rlds_isba'          : {'varname':           'rlds_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Downwelling LW Radiation at surface'}, 
    'rlus_isba'          : {'varname':           'rlus_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Upwelling LW Radiation at surface'}, 
    'rls_isba'           : {'varname':            'rls_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Net LW Radiation at surface'}, 
    'rnet_isba'          : {'varname':           'rnet_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Net Radiation at surface'}, 
    'hfls_isba'          : {'varname':           'hfls_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Surface Latent Heat Flux'}, 
    'hfsbl_isba'         : {'varname':          'hfsbl_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Surface Latent Heat Flux due to Sublimation'}, 
    'hfss_isba'          : {'varname':           'hfss_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Surface Sensible Heat Flux'}, 
    'hfdsl_isba'         : {'varname':          'hfdsl_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Downward Heat Flux at Surface'}, 
    'hfdsn_isba'         : {'varname':          'hfdsn_isba', 'units':          'W m-2', 'coef':         1, 'name':'ISBA Downward Snow Heat Flux at Surface'}, 
    'potet_isba'         : {'varname':          'potet_isba', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'ISBA Potential Evapotranspiration'}, 
    'et_isba'            : {'varname':             'et_isba', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'ISBA Total Evapotranspiration'}, 
    'tran_isba'          : {'varname':           'tran_isba', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'ISBA Plant Transpiration'}, 
    'ustar_isba'         : {'varname':          'ustar_isba', 'units':          'm s-1', 'coef':         1, 'name':'ISBA Surface Friction Velocity'}, 
    'tauu_isba'          : {'varname':           'tauu_isba', 'units':             'Pa', 'coef':         1, 'name':'ISBA Zonal Surface Stress'}, 
    'tauv_isba'          : {'varname':           'tauv_isba', 'units':             'Pa', 'coef':         1, 'name':'ISBA Meridional Surface Stress'}, 
    'tau_isba'           : {'varname':            'tau_isba', 'units':             'Pa', 'coef':         1, 'name':'ISBA Surface Stress'}, 
    'tg_isba'            : {'varname':             'tg_isba', 'units':              'K', 'coef':         1, 'name':'ISBA Soil Temperature'}, 
    'ts_isba'            : {'varname':             'ts_isba', 'units':              'K', 'coef':         1, 'name':'ISBA Surface Temperature'}, 
    'tg1_isba'           : {'varname':            'tg1_isba', 'units':              'K', 'coef':         1, 'name':'ISBA First Soil Layer Temperature'}, 
    'qs_isba'            : {'varname':             'qs_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Surface Moisture'}, 
    'mrsol_isba'         : {'varname':          'mrsol_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Total Water Content of Soil Layers'}, 
    'mrsll_isba'         : {'varname':          'mrsll_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Liquid Water Content of Soil Layers'}, 
    'mrsfl_isba'         : {'varname':          'mrsfl_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Frozen Water Content of Soil Layers'}, 
    'wg_isba'            : {'varname':             'wg_isba', 'units':         'm3 m-3', 'coef':         1, 'name':'ISBA Liquid Water Content of Soil Layers'}, 
    'wgi_isba'           : {'varname':            'wgi_isba', 'units':         'm3 m-3', 'coef':         1, 'name':'ISBA Frozen Water Content of Soil Layers'}, 
    'mrsos_isba'         : {'varname':          'mrsos_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Top Soil Reservoir'}, 
    'rzwc_isba'          : {'varname':           'rzwc_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Root Soil Reservoir'}, 
    'mrso_isba'          : {'varname':           'mrso_isba', 'units':         'kg m-2', 'coef':         1, 'name':'ISBA Total Soil Reservoir'}, 
    'albsrfc_isba'       : {'varname':        'albsrfc_isba', 'units':              '-', 'coef':         1, 'name':'ISBA Surface Albedo'}, 
    'z0_isba'            : {'varname':             'z0_isba', 'units':              'm', 'coef':         1, 'name':'ISBA Rougness Length for Momentum'}, 
    'z0h_isba'           : {'varname':            'z0h_isba', 'units':              'm', 'coef':         1, 'name':'ISBA Rougness Length for Thermodynamics'}, 
    'area_fraction_patch': {'varname': 'area_fraction_patch', 'units':              '-', 'coef':         1, 'name':'ISBA Patch Area Fraction'}, 
    'lai_patch'          : {'varname':           'lai_patch', 'units':              '-', 'coef':         1, 'name':'Leaf Area Index per ISBA Patch'}, 
    'veg_patch'          : {'varname':           'veg_patch', 'units':              '-', 'coef':         1, 'name':'Vegetation Fraction per ISBA Patch'}, 
    'tas_patch'          : {'varname':           'tas_patch', 'units':              'K', 'coef':         1, 'name':'2-m Temperature per ISBA Patch'},
    'huss_patch'         : {'varname':          'huss_patch', 'units':        'kg kg-1', 'coef':         1, 'name':'2-m Specific Humidity per ISBA Patch'},
    'hurs_patch'         : {'varname':          'hurs_patch', 'units':              '-', 'coef':         1, 'name':'2-m Relative Humidity per ISBA Patch'},
    'sfcWind_patch'      : {'varname':       'sfcWind_patch', 'units':          'm s-1', 'coef':         1, 'name':'10-m Wind Speed per ISBA Patch'},
    'rsds_patch'         : {'varname':          'rsds_patch', 'units':          'W m-2', 'coef':         1, 'name':'Downwelling SW Radiation at surface per ISBA Patch'}, 
    'rsus_patch'         : {'varname':          'ruds_patch', 'units':          'W m-2', 'coef':         1, 'name':'Upwelling SW Radiation at surface per ISBA Patch'}, 
    'rss_patch'          : {'varname':           'rss_patch', 'units':          'W m-2', 'coef':         1, 'name':'Net SW Radiation at surface per ISBA Patch'}, 
    'rlds_patch'         : {'varname':          'rlds_patch', 'units':          'W m-2', 'coef':         1, 'name':'Downwelling LW Radiation at surface per ISBA Patch'}, 
    'rlus_patch'         : {'varname':          'rlus_patch', 'units':          'W m-2', 'coef':         1, 'name':'Upwelling LW Radiation at surface per ISBA Patch'}, 
    'rls_patch'          : {'varname':           'rls_patch', 'units':          'W m-2', 'coef':         1, 'name':'Net LW Radiation at surface per ISBA Patch'},    
    'rnet_patch'         : {'varname':          'rnet_patch', 'units':          'W m-2', 'coef':         1, 'name':'Net Radiation at surface per ISBA Patch'},
    'hfls_patch'         : {'varname':          'hfls_patch', 'units':          'W m-2', 'coef':         1, 'name':'Surface Latent Heat Flux per ISBA Patch'}, 
    'hfsbl_patch'        : {'varname':         'hfsbl_patch', 'units':          'W m-2', 'coef':         1, 'name':'Surface Latent Heat Flux due to Sublimation per ISBA Patch'}, 
    'hfss_patch'         : {'varname':          'hfss_patch', 'units':          'W m-2', 'coef':         1, 'name':'Surface Sensible Heat Flux per ISBA Patch'},
    'hfdsl_patch'        : {'varname':         'hfdsl_patch', 'units':          'W m-2', 'coef':         1, 'name':'Downward Heat Flux at Surface per ISBA Patch'},
    'hfdsn_patch'        : {'varname':         'hfdsn_patch', 'units':          'W m-2', 'coef':         1, 'name':'Downward Snow Heat Flux at Surface per ISBA Patch'},
    'potet_patch'        : {'varname':         'potet_patch', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'Potential Evapotranspiration per ISBA Patch'}, 
    'et_patch'           : {'varname':            'et_patch', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'Total Evapotranspiration per ISBA Patch'}, 
    'tran_patch'         : {'varname':          'tran_patch', 'units':     'kg m-2 s-1', 'coef':         1, 'name':'Plant Transpiration per ISBA Patch'}, 
    'ustar_patch'        : {'varname':         'ustar_patch', 'units':          'm s-1', 'coef':         1, 'name':'Surface Friction Velocity per ISBA Patch'}, 
    'tauu_patch'         : {'varname':          'tauu_patch', 'units':             'Pa', 'coef':         1, 'name':'Zonal Surface Stress per ISBA Patch'}, 
    'tauv_patch'         : {'varname':          'tauv_patch', 'units':             'Pa', 'coef':         1, 'name':'Meridional Surface Stress per ISBA Patch'}, 
    'tau_patch'          : {'varname':           'tau_patch', 'units':             'Pa', 'coef':         1, 'name':'Surface Stress per ISBA Patch'},
    'tg_patch'           : {'varname':            'tg_patch', 'units':              'K', 'coef':         1, 'name':'Soil Temperature per ISBA Patch'},    
    'ts_patch'           : {'varname':            'ts_patch', 'units':              'K', 'coef':         1, 'name':'Surface Temperature per ISBA Patch'}, 
    'qs_patch'           : {'varname':            'qs_patch', 'units':         'kg m-2', 'coef':         1, 'name':'Surface Moisture per ISBA Patch'}, 
    'mrsol_patch'        : {'varname':         'mrsol_patch', 'units':         'kg m-2', 'coef':         1, 'name':'Total Water Content of Soil Layers per ISBA Patch'}, 
    'wg_patch'           : {'varname':            'wg_patch', 'units':         'm3 m-3', 'coef':         1, 'name':'Liquid Water Content of Soil Layers per ISBA Patch'}, 
    'wgi_patch'          : {'varname':           'wgi_patch', 'units':         'm3 m-3', 'coef':         1, 'name':'Frozen Water Content of Soil Layers per ISBA Patch'},
    'albsrfc_patch'      : {'varname':       'albsrfc_patch', 'units':              '-', 'coef':         1, 'name':'Surface Albedo per ISBA Patch'}, 
    'z0_patch'           : {'varname':            'z0_patch', 'units':              'm', 'coef':         1, 'name':'Rougness Length for Momentum per ISBA Patch'}, 
    'z0h_patch'          : {'varname':           'z0h_patch', 'units':              'm', 'coef':         1, 'name':'Rougness Length for Thermodynamics per ISBA Patch'},    
}
